version: '3'
services:
  loop_closure:
    image: tccoin/simple_slam_loop_closure:latest
    volumes:
      - .:/src
      - /media/sdg1/rzh/kitti/kitti/sequences/:/kitti
      - /home/junzhewu/:/ws
    working_dir: /src
    command: bash
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_REQUIRE_CUDA=cuda>=9.0
