version: '3'
services:
  loop_closure:
    image: tccoin/simple_slam_loop_closure:latest
    volumes:
      - /home/link/Projects/curly_slam/data/:/dataset
      - /home/link/Projects/simple_slam_loop_closure/:/ws
    working_dir: /ws
    command: bash
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_REQUIRE_CUDA=cuda>=9.0
